apiVersion: v1
kind: ConfigMap
metadata:
  name: high-steak-config
  namespace: apps
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://db-apps-mysql-svc:3306/high_steak?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: root
  SERVER_SERVLET_CONTEXT_PATH: /api
  CORS_ALLOWED_ORIGINS: https://steaks.apps.hossam.io
  UPLOADS_DIR: /app/uploads
  BOOTSTRAP_ADMIN_ENABLED: "true"
  HTTP_ACCESS_LOG_ENABLED: "true"
