{{- if .Values.persistence.uploads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "high-steak.fullname" . }}-uploads
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "high-steak.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  {{- if .Values.persistence.uploads.storageClass }}
  storageClassName: {{ .Values.persistence.uploads.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }}
