apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "high-steak.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "high-steak.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.configMap.SPRING_DATASOURCE_URL | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.configMap.SPRING_DATASOURCE_USERNAME | quote }}
  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.configMap.SERVER_SERVLET_CONTEXT_PATH | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.configMap.CORS_ALLOWED_ORIGINS | quote }}
  UPLOADS_DIR: {{ .Values.configMap.UPLOADS_DIR | quote }}
  BOOTSTRAP_ADMIN_ENABLED: {{ .Values.configMap.BOOTSTRAP_ADMIN_ENABLED | quote }}
  HTTP_ACCESS_LOG_ENABLED: {{ .Values.configMap.HTTP_ACCESS_LOG_ENABLED | quote }}
