{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "high-steak.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "high-steak.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "high-steak.fullname" . }}-api-svc
                port:
                  number: {{ .Values.apiService.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "high-steak.fullname" . }}-web-svc
                port:
                  number: {{ .Values.service.port }}
{{- end }}
