{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "high-steak.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.data.JWT_SECRET | quote }}
  BOOTSTRAP_ADMIN_USERNAME: {{ .Values.secret.data.BOOTSTRAP_ADMIN_USERNAME | quote }}
  BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secret.data.BOOTSTRAP_ADMIN_PASSWORD | quote }}
  BOOTSTRAP_ADMIN_EMAIL: {{ .Values.secret.data.BOOTSTRAP_ADMIN_EMAIL | quote }}
  BOOTSTRAP_ADMIN_DISPLAY_NAME: {{ .Values.secret.data.BOOTSTRAP_ADMIN_DISPLAY_NAME | quote }}
{{- end }}
